### ISSUE TITLE
基于 Less 的多主题实现

### ISSUE THREAD

**Issue by NameWjp** [NameWjp/blog#65]
实现原理是通过 Less 编译多份主题，首先需要定义多份主题样式变量文件
```less
// defaultTheme.less
@text-color: #333;
```
```less
// darkTheme.less
@text-color: #fff;
```
之后需要一个文件提供引入变量和编译的功能
```less
// theme.less
@themes: default, dark;

.import-vars(@theme) when (@theme = default) {
  @import './defaultTheme.less';
}

.import-vars(@theme) when (@theme = dark) {
  @import './darkTheme.less';
}

.generator-themes(@index) when (@index =< length(@themes)) {
  .import-vars(extract(@themes, @index));
  .add-prefix(extract(@themes, @index));
  .generator-themes((@index + 1));
}

.generator-themes(1);
```
之后只需要通过 add-prefix 函数去生成多主题即可
```less
// global.less
@import './theme.less';

.add-prefix(@theme) {
  .global-theme-@{theme} {
    .text {
      color: @text-color;
    }
  }
}
```
引入 global.less 后会生成类名分别为 global-theme-default 和 global-theme-dark 两套 css 样式

需要注意两个问题:   
1.  less 在执行 mixins 的时候会在当前作用域查找，如果查找到则会合并当前作用域的 mixins，如果查找不到才会查找父级作用域的 mixins，所以建议将 mixins 写到一处，否则会出现 mixins 缺失执行的问题。
2. add-prefix 需要定义到导入变量的地方，less会存在变量冒泡的行为，当且仅当具有该名称的变量不存在于父或祖先的上下文中时，Less 会将变量从 mixin 调用上下文冒泡到其父上下文。相关issues: [https://github.com/less/less.js/issues/3091](https://github.com/less/less.js/issues/3091)
